### ISSUE TITLE
The call widget has an error. Message: The call widget isn't logged in.

### ISSUE THREAD

**Issue by JuniperdROAR** [ringcentral/ringcentral-integration-for-hubspot#11]
Can you help with this error message

The call widget has an error.
Message: The call widget isn't logged in.

This is appearing with the integration with HubSpot

Thank you
![Annotation 2020-08-21 100313](https://user-images.githubusercontent.com/70013333/90876384-8390e000-e39a-11ea-8d5b-31eda5b9b6ac.jpg)

**Comment by 87Marc** [comment]
Is this happening in Chrome?  If not which Browser?

**Comment by JuniperdROAR** [comment]
It’s within HubSpot, it’s not the Chrome extension.

David Juniper
Group Event Director
ROAR B2B
+44 (0) 7366 605724
________________________________

**Comment by 87Marc** [comment]
David,

Just to be clear I'm not on the dev team, but I know one of the first
questions they are going to ask is which browser you are running.  Hubspot
runs in a browser as it isn't a standalone application.  You are likely
using either Chrome, Edge, or Firefox.  Most likely Chrome since you
mention the other add-in for Chrome, but I thought I would save them time
and confirm with you.

Just trying to help.

Regards,

Marc

**Comment by JuniperdROAR** [comment]
Correct, Chrome.

Thank you.

David Juniper
Group Event Director
ROAR B2B
+44 (0) 7366 605724
________________________________

**Comment by zxdong262** [comment]
@JuniperdROAR @87Marc Hi all, thank you for the feedback, it is fixed now, you can just reload the page, it will be OK now
